language: node_js

node_js: "12"

cache:
  directories:
    - node_modules

before_install:
  - sudo apt-get install postgresql-9.5

before_script:
  - psql -c 'CREATE DATABASE travis;' -U postgres
  - psql -c 'CREATE DATABASE test;' -U postgres

script: 
  - npm test

after_script:
  - npm install coveralls && npm run coverage
