/**
 * Data to seed into the db
 * All tasks including details.
 */
const data = [
  {
    customerFirstName: "John",
    customerLastName: "Doe",
    personnelFirstName: "Jacob",
    personnelLastName: "Zouma",
    customePhoneNo: "0723456723",
    agentId: "1234",
    assigned: Date.now(),
    inProgress: Date.now(),
    completed: false,
    deferred: Date.now(),
    status: "Deffered",
    location: "Nairobi",
    gender: "Male",
    age: 23,
    accessCode: 1,
    splashPage: 2,
    mpesa: null,
    autoPlay: null,
    comments: "No Answer",
    registration: "Self"
  },
  {
    customerFirstName: "Elias",
    customerLastName: "Mathias",
    personnelFirstName: "Jacob",
    personnelLastName: "Kaino",
    customePhoneNo: "0793456793",
    agentId: null,
    assigned: Date.now(),
    inProgress: Date.now(),
    completed: false,
    deferred: Date.now(),
    status: "Deffered",
    location: "Nairobi",
    gender: "Male",
    age: 12,
    accessCode: 1,
    splashPage: 1,
    mpesa: null,
    autoPlay: null,
    comments: "No Answer",
    registration: "Self"
  },
  {
    customerFirstName: "John",
    customerLastName: "Doe",
    personnelFirstName: "Jacob",
    personnelLastName: "Zouma",
    customePhoneNo: "0729056723",
    agentId: null,
    assigned: Date.now(),
    inProgress: Date.now(),
    completed: false,
    deferred: Date.now(),
    status: "Deffered",
    location: "Nairobi",
    gender: "Male",
    age: 21,
    accessCode: 1,
    splashPage: 2,
    mpesa: null,
    autoPlay: null,
    comments: "No Answer",
    registration: "Self"
  },
  {
    customerFirstName: "John",
    customerLastName: "Doe",
    personnelFirstName: "Jacob",
    personnelLastName: "Zouma",
    customePhoneNo: "0723456723",
    agentId: "1234",
    assigned: Date.now(),
    inProgress: Date.now(),
    completed: false,
    deferred: Date.now(),
    status: "Deffered",
    location: "Nairobi",
    gender: "Male",
    age: 23,
    accessCode: 1,
    splashPage: 2,
    mpesa: null,
    autoPlay: null,
    comments: "No Answer",
    registration: "Self"
  },
  {
    customerFirstName: "John",
    customerLastName: "Doe",
    personnelFirstName: "Jacob",
    personnelLastName: "Zouma",
    customePhoneNo: "0723456723",
    agentId: null,
    assigned: Date.now(),
    inProgress: Date.now(),
    completed: false,
    deferred: Date.now(),
    status: "Deffered",
    location: "Nairobi",
    gender: "Male",
    age: 23,
    accessCode: 1,
    splashPage: 2,
    mpesa: null,
    autoPlay: null,
    comments: "No Answer",
    registration: "Self"
  },
  {
    customerFirstName: "John",
    customerLastName: "Doe",
    personnelFirstName: "Jacob",
    personnelLastName: "Zouma",
    customePhoneNo: "0723456723",
    agentId: "1234",
    assigned: Date.now(),
    inProgress: Date.now(),
    completed: false,
    deferred: Date.now(),
    status: "Deffered",
    location: "Nairobi",
    gender: "Male",
    age: 23,
    accessCode: 1,
    splashPage: 2,
    mpesa: null,
    autoPlay: null,
    comments: "No Answer",
    registration: "Self"
  },
  {
    customerFirstName: "John",
    customerLastName: "Doe",
    personnelFirstName: "Jacob",
    personnelLastName: "Zouma",
    customePhoneNo: "0723456723",
    agentId: "1234",
    assigned: Date.now(),
    inProgress: Date.now(),
    completed: false,
    deferred: Date.now(),
    status: "Deffered",
    location: "Nairobi",
    gender: "Male",
    age: 23,
    accessCode: 1,
    splashPage: 2,
    mpesa: null,
    autoPlay: null,
    comments: "No Answer",
    registration: "Self"
  },
  {
    customerFirstName: "John",
    customerLastName: "Doe",
    personnelFirstName: "Jacob",
    personnelLastName: "Zouma",
    customePhoneNo: "0723456723",
    agentId: "1234",
    assigned: Date.now(),
    inProgress: Date.now(),
    completed: false,
    deferred: Date.now(),
    status: "Deffered",
    location: "Nairobi",
    gender: "Male",
    age: 23,
    accessCode: 1,
    splashPage: 2,
    mpesa: null,
    autoPlay: null,
    comments: "No Answer",
    registration: "Self"
  },
  {
    customerFirstName: "John",
    customerLastName: "Doe",
    personnelFirstName: "Jacob",
    personnelLastName: "Zouma",
    customePhoneNo: "0723456723",
    agentId: "1234",
    assigned: Date.now(),
    inProgress: Date.now(),
    completed: false,
    deferred: Date.now(),
    status: "Deffered",
    location: "Nairobi",
    gender: "Male",
    age: 23,
    accessCode: 1,
    splashPage: 2,
    mpesa: null,
    autoPlay: null,
    comments: "No Answer",
    registration: "Self"
  },
  {
    customerFirstName: "John",
    customerLastName: "Doe",
    personnelFirstName: "Jacob",
    personnelLastName: "Zouma",
    customePhoneNo: "0723456723",
    agentId: "1234",
    assigned: Date.now(),
    inProgress: Date.now(),
    completed: false,
    deferred: Date.now(),
    status: "Deffered",
    location: "Nairobi",
    gender: "Male",
    age: 23,
    accessCode: 1,
    splashPage: 2,
    mpesa: null,
    autoPlay: null,
    comments: "No Answer",
    registration: "Self"
  },
  {
    customerFirstName: "John",
    customerLastName: "Doe",
    personnelFirstName: "Jacob",
    personnelLastName: "Zouma",
    customePhoneNo: "0723456723",
    agentId: "1234",
    assigned: Date.now(),
    inProgress: Date.now(),
    completed: false,
    deferred: Date.now(),
    status: "Deffered",
    location: "Nairobi",
    gender: "Male",
    age: 23,
    accessCode: 1,
    splashPage: 2,
    mpesa: null,
    autoPlay: null,
    comments: "No Answer",
    registration: "Self"
  },
  {
    customerFirstName: "John",
    customerLastName: "Doe",
    personnelFirstName: "Jacob",
    personnelLastName: "Zouma",
    customePhoneNo: "0723456723",
    agentId: "1234",
    assigned: Date.now(),
    inProgress: Date.now(),
    completed: false,
    deferred: Date.now(),
    status: "Deffered",
    location: "Nairobi",
    gender: "Male",
    age: 23,
    accessCode: 1,
    splashPage: 2,
    mpesa: null,
    autoPlay: null,
    comments: "No Answer",
    registration: "Self"
  },
  {
    customerFirstName: "John",
    customerLastName: "Doe",
    personnelFirstName: "Jacob",
    personnelLastName: "Zouma",
    customePhoneNo: "0723456723",
    agentId: "1234",
    assigned: Date.now(),
    inProgress: Date.now(),
    completed: false,
    deferred: Date.now(),
    status: "Deffered",
    location: "Nairobi",
    gender: "Male",
    age: 23,
    accessCode: 1,
    splashPage: 2,
    mpesa: null,
    autoPlay: null,
    comments: "No Answer",
    registration: "Self"
  },
  {
    customerFirstName: "John",
    customerLastName: "Doe",
    personnelFirstName: "Jacob",
    personnelLastName: "Zouma",
    customePhoneNo: "0723456723",
    agentId: "1234",
    assigned: Date.now(),
    inProgress: Date.now(),
    completed: false,
    deferred: Date.now(),
    status: "Deffered",
    location: "Nairobi",
    gender: "Male",
    age: 23,
    accessCode: 1,
    splashPage: 2,
    mpesa: null,
    autoPlay: null,
    comments: "No Answer",
    registration: "Self"
  },
  {
    customerFirstName: "John",
    customerLastName: "Doe",
    personnelFirstName: "Jacob",
    personnelLastName: "Zouma",
    customePhoneNo: "0723456723",
    agentId: "1234",
    assigned: Date.now(),
    inProgress: Date.now(),
    completed: false,
    deferred: Date.now(),
    status: "Deffered",
    location: "Nairobi",
    gender: "Male",
    age: 23,
    accessCode: 1,
    splashPage: 2,
    mpesa: null,
    autoPlay: null,
    comments: "No Answer",
    registration: "Self"
  }
];

export default data;
